# 异常处理

## 渲染错误边界

> 组件渲染过程中只要有一个环节除了问题,就会造成整个组件的渲染失败,越靠近根组件,造成的影响就越大

- React 中处理异常的生命周期
  - `componentDidCatch`
  - `static getDerivedStateFromError`

## componentDidCatch

- 可以捕获异常并接收两个参数
  - error => 抛出的错误
  - info => 带有 `componentStack key` 的对象，其中包含有关组件引发错误的栈信息

在 `componentDidCatch` 中触发 `setState` 来处理异常

```js
import React from "react";
function ErrorComponent() {
  return;
}

export function Test() {
  return <div>have a good day!</div>;
}

export default class Index extends React.Component {
  state = {
    hasError: false,
  };
  componentDidCatch(...args) {
    console.log(args); //打印错误
    this.setState({
      // 降级 ui
      hasError: true,
    });
  }
  render() {
    return (
      <div>
        {this.state.hasError ? <div>发生了错误</div> : <ErrorComponent />}
        <div>error test</div>
        <Test />
      </div>
    );
  }
}
```

- 调用 `setState` 控制组件渲染,并做一些错误拦截功能
- 监控组件,发生错误,上报错误日志

## static getDerivedStateFromError

`getDerivedStateFromError`是静态方法,不能调用 `this.setState`,但返回值可以合并到 state 作为渲染使用

```js
class Index extends React.Component {
  state = {
    hasError: false,
  };
  static getDerivedStateFromError() {
    return { hasError: true };
  }
  render() {
    <div>
      {this.state.hasError ? <div>发生了错误</div> : <ErrorComponent />}
      <div>error test</div>
      <Test />
    </div>;
  }
}
```
